### ISSUE TITLE
auto eating when opening backpack 

### ISSUE THREAD

**Issue by Azturax** [Stein-N/Resource-Backpacks#22]
I found a bug where when i hold food (specifically atm potatos) 
and open the backpack (diamond if that matters) 
my character would start eating automatically

**Comment by Stein-N** [comment]
Do you have the Backpack in your Off hand or Equipped and open it via the Key Bind?

**Comment by Azturax** [comment]
i have the backpack in my right hand and potatos in the offhand

**Comment by Azturax** [comment]
i open it via rightclick

**Comment by Stein-N** [comment]
What Mod version and wich loader do you use?

**Comment by Azturax** [comment]
resource_backpacks-fabric-1.21.3-0.9.3-BETA.jar
latest release on modrinth and latest fabric loader 0.16.9

**Comment by Stein-N** [comment]
I released version 0.10.0-BETA prior today, but i would assume the bug also appears in that version

**Comment by Azturax** [comment]
just updated, changed config for open_from_inventory to true. Yes bug is still there.

**Comment by Stein-N** [comment]
new version that fixes the issue is available on modrinth. Thanks for reporting :)
